# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhenoDbGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=10, unique=True, verbose_name='Gene ID')),
                ('gene', models.CharField(max_length=15, verbose_name='Gene')),
            ],
            options={
                'verbose_name': 'Gene',
                'verbose_name_plural': 'Genes',
            },
        ),
        migrations.CreateModel(
            name='PhenoDbHpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpo_id', models.CharField(max_length=10, unique=True, verbose_name='HPO ID')),
                ('hpo_name', models.CharField(max_length=255, verbose_name='Nome do HPO')),
                ('gene', models.ManyToManyField(related_name='hpo', to='problema_1.PhenoDbGene')),
            ],
            options={
                'verbose_name': 'HPO',
                'verbose_name_plural': 'HPO',
            },
        ),
    ]
